### ISSUE TITLE
/usr/bin/play: not found | On Raspberry Pi OS

### ISSUE THREAD

**Issue by hemesh-t** [mdoege/big_ben#1]
Trying to run this on raspberry pi / os and facing the below error.

![2023-07-12-140504_1920x1080_scrot](https://github.com/mdoege/big_ben/assets/7971536/152d12e9-59a8-4ae6-8b5c-fb2d321d45ee)

Is there a way to run this program on raspberry pi?

**Comment by mdoege** [comment]
/usr/bin/play is contained in the SoX package (e.g. https://packages.debian.org/bookworm/sox), so you need to install that…
